version: '3'
services:
    nginx-server:
        image: "nginx:1.17"
        volumes:
            - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./project:/var/www/html
        networks:
            - dnetwork
        ports:
            - "8080:80"
    php-fpm:
        build:
            context: .
            dockerfile: ./config/docker/containers/php7.2-fpm/Dockerfile
        volumes:
            - ./project:/var/www/html
        networks:
            - dnetwork
        ports:
            - "9090:9000"
    composer:
        image: "composer:1.9"
        volumes:
            - ./project:/app
        command: install
    mysql-server:
        image: "mysql:8.0"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ROOT_PASSWORD="qwerty"
        ports:
            - "33066:3306"
        volumes:
            - "./database:/var/lib/mysql"
networks:
    dnetwork:
        driver: bridge
